# Generated by Django 5.2.6 on 2025-09-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scanner', '0004_add_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='archive_old_backups',
            field=models.BooleanField(default=True, help_text='Archive old backups instead of deleting them'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='archive_path',
            field=models.CharField(default='backups/archives/', help_text='Path for archived backups', max_length=500),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='retention_months',
            field=models.PositiveIntegerField(default=6, help_text='Number of months to keep individual backups before archiving'),
        ),
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_name', models.CharField(help_text='Name of the archive file', max_length=255)),
                ('archive_path', models.CharField(help_text='Full path to the archive file', max_length=500)),
                ('archive_size', models.BigIntegerField(help_text='Size of the archive in bytes')),
                ('backup_count', models.PositiveIntegerField(help_text='Number of backups in this archive')),
                ('date_range_start', models.DateTimeField(help_text='Start date of backups in archive')),
                ('date_range_end', models.DateTimeField(help_text='End date of backups in archive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='network_scanner.backupconfig')),
            ],
        ),
    ]
