# Generated by Django 5.2.6 on 2025-09-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scanner', '0005_backupconfig_archive_old_backups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='auto_push_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic push of backups to remote location'),
        ),
    ]
