# Generated by Django 5.2.6 on 2025-09-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scanner', '0006_add_auto_push_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('enable_hostname_search', models.BooleanField(default=True, help_text='Enable hostname search functionality')),
                ('enable_ip_search', models.BooleanField(default=True, help_text='Enable IP address search functionality')),
                ('enable_suggestions', models.BooleanField(default=True, help_text='Enable search suggestions dropdown')),
                ('min_search_length', models.PositiveIntegerField(default=2, help_text='Minimum characters before showing suggestions')),
                ('max_suggestions', models.PositiveIntegerField(default=10, help_text='Maximum number of suggestions to show')),
                ('search_fields', models.JSONField(blank=True, default=list, help_text='Fields to search in (JSON array of field names)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable this search configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
